apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.3
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: lab
          - name: MYSQL_DATABASE
            value: app
          - name: MYSQL_USER
            value: app
          - name: MYSQL_PASSWORD
            value: lab
